### ISSUE TITLE
LAV Spam

### ISSUE THREAD

**Issue by bozocow** [S5SS/dok-patch#2]
LAV's currently beat Sandskimmers and strikecraft tend to be too strong in general

**Comment by RoBeY4Gate** [comment]
I think people agreed that the cooldown on the speed boost (assault pack upgrade for LAV) could use an increase.

30seconds is pretty short but 60seconds feels a tad long for the price of it. So maybe a medium of 45seconds.

Note: if it is desired to be longer cooldown anything past 60seconds a cost reduction for this upgrade should be looked into then?

**Comment by S5SS** [comment]
45 sounds reasonable to me

**Comment by bozocow** [comment]
Like Last Rites was saying increasing the cooldown there is a good start, but I think we need to go further of course.

My suggestions is: Cooldown increased to 45 sec., 15% RoF increase to LAV's from last patch removed, LAV range reduced from 900 to 800

This would work because LAV's still have the range advantage, meaning the micro and unit interaction doesn't change, but Sandskimmers now win if they get on top of the LAV's (which was the intention from release) and the battle should be winnable from either side now.

**Comment by RoBeY4Gate** [comment]
Bozo try and see if you can test with garm, he’s looking to test with people.

**Comment by Garmilator** [comment]
My suggestion is:

1.Increase CD for boost to 40 Seconds. Then slightly nerf on boost speed. 6-10
Right now so many times is Boost that allow Coal/Soban do run by kills. WIthout suffer major dmg back.

2. If was possible lower dmg with 0.5 or simulate lower rate of fire to deal 0.5 dmg less.
This allow bigger marginal window for proper micro for gaal/khan player move out there dmg skimmer to survive.

Think these changes enough to even out balance between units.
