### ISSUE TITLE
Turrets too oppressive? 

### ISSUE THREAD

**Issue by RoBeY4Gate** [S5SS/dok-patch#3]
Many have commented that turrets (mainly coal ground to ground turret) have been too strong and cause balance problems.

Please post ideas/other issues they bring up!

**Comment by RoBeY4Gate** [comment]
Would reducing the range of Coalition turret (ground) be enough and if so what will that range be?

**Comment by bozocow** [comment]
If we go with just reducing range I think it has to be pretty drastic.  Maybe 800 to bring it in line with the LAV change I suggested?  (The current range is 1200, double the range of a sandskimmer)

**Comment by RoBeY4Gate** [comment]
Garm suggested to try it at 1000 range first and see how it is.
