### ISSUE TITLE
Khaan seige cruisers good at everything

### ISSUE THREAD

**Issue by S5SS** [S5SS/dok-patch#4]
High range + high hp + high dps + fast + regening health + good vs most units at close range too even battle cruisers with enough numbers. To me the auto attack seems a little too good, perhaps double the ROF but halve the damage so they become much worse vs armored units (thats what hgc are for, khaan rarely build them because they don't even need to imo)

**Comment by S5SS** [comment]
High range + high hp and dps + fast + regening health + good vs most units at close range too even battle cruisers with enough numbers

**Comment by bozocow** [comment]
I think damage, barrage, etc. should stay the same and health should be reduced from 3350 to 2100, and armor from 16 to 14.  Nothing too drastic, but small changes to make them less tanky against rails.
