### ISSUE TITLE
Super Weapons

### ISSUE THREAD

**Issue by RoBeY4Gate** [S5SS/dok-patch#5]
Obvious....

Coal high ground Nuke should be removed? 

Other super weapon opinions?

**Comment by S5SS** [comment]
Yup high ground nukes should be removed imo and I think cool downs should be higher too. Personally I would rather nukes were area denial like the soban nuke instead of insta I win abilities if you get a good hit so maybe the nuke speed should be made slower to give more time to move

**Comment by bozocow** [comment]
I think there are a couple of ways to approach this.

The nuke is so fast you can never dodge, so reducing the speed fixes this issue.  But there's still the imbalance that the nuke will still hit carriers, and the Gaalsien/Soban don't have anything that can compare.

If Nukes were removed entirely and kept to campaign only I would be honestly quite happy with it, but that seems like an unpopular change.  Instead, we can increase the cost drastically (maybe 500 CU, 500 RU) to ensure that people only use nukes when the yield will be very high.

**Comment by Garmilator** [comment]
At moment you can dodge nuke. With high ground dmg removed from Nuke.
Need only pay attention and yes short distance should be hard to avoid honestly.

As you look on high levels game Nuke is not that devasting effect on army (Descara vs Me games)
More people need spread out there units and engage proberly.

Will stop mainly these following stuff.
1. Long distance main eco nuke hit. 7500 dmg on main eco or other eco sites. (Production cruiser/support cruiser)
2. Instant cruiser kills on Coal/Soban units or other high hp unit. (Khaan carrier 12.5k->7.5k dmg instant gg)

------------------------------------------------------------------------
These changes will allow people survive devasting one shoot at eco on many maps. Example teeth map (Short distance between enemy carrier/your main eco site.)

This will fix alot of issue at moment with how high ground devasting nuke is.
Overall all carrier ability should have high ground dmg apply removed.

More so I want more changes on Soban carrier to become honestly useful in a combat. Then some dead weight carrier.
