### ISSUE TITLE
Working out obscure unit names

### ISSUE THREAD

**Issue by S5SS** [S5SS/dok-patch#7]
Some of the unit names I dumped are a little vague as to what they are, for example:
C_Escort_UnitAttributesAsset_MP
C_HAC_UnitAttributesAsset_MP
C_HAC_Upgrade01_UnitAttributesAsset_MP
G_StarHull_UnitAttributesAsset_MP
G_StarHull_Upgrade01_UnitAttributesAsset_MP
G_Catamaran_UnitAttributesAsset_MP
G_Catamaran_Upgrade01_UnitAttributesAsset_MP

working out what they are will be needed to change units that are otherwise missing ei:
LAV
AAV
Heavy rails
Assault rails
etc

**Comment by bozocow** [comment]
I would assume that C_Escort is the LAV and C_HAC is the AAV (LAV's are like escorts and HAC sounds like Heavy Armor Chassis).

I'm not sure about the other ones but I would suspect that StarHull is the heavy rail and Catamaran is the Assault Rail.

**Comment by S5SS** [comment]
You're probably right about the HAC since I found this: C_HAC_Weapon_Ballistic_Smoke_MP so looks like an AAV to me, another unit that is missing is the assault cruiser. Soban seems to have it so maybe coal uses the same version.

**Comment by S5SS** [comment]
catamaran: as
catamaran u1: ms
starhull: heavy rail
starhull u1: assault rail
escort: lav (Thanks to AGameAnx)
