### ISSUE TITLE
Tactical Bomber

### ISSUE THREAD

**Issue by S5SS** [S5SS/dok-patch#8]
This unit is trash, for a start it costs way too much, arrives too late, you can only get 3 of them and there is like a 50% chance it wont even shoot at what its attacking. Possibly some changes to turn speed and fire range are needed in order for it to hit its target and the cost/tech cost of the unit seems a little too high.

**Comment by bozocow** [comment]
Agreed.  I think the damage of the unit is mostly okay, it's just tech and unit costs, and like you said its tendency not to fire, that hold it back.
